# Generated by Django 5.2.3 on 2025-06-27 13:33

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible_columns', models.JSONField(default=list, help_text='List of column names to display for this organization')),
                ('column_order', models.JSONField(default=list, help_text='Order of columns to display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='employee_search.organization')),
            ],
            options={
                'db_table': 'organization_configs',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_index=True, max_length=100)),
                ('last_name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(db_index=True, max_length=100)),
                ('position', models.CharField(db_index=True, max_length=100)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('terminated', 'Terminated'), ('on_leave', 'On Leave')], db_index=True, default='active', max_length=20)),
                ('hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employee_search.organization')),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['last_name', 'first_name'],
                'indexes': [models.Index(fields=['organization', 'status'], name='employees_organiz_9abb4d_idx'), models.Index(fields=['organization', 'department'], name='employees_organiz_d5774c_idx'), models.Index(fields=['organization', 'location'], name='employees_organiz_201e10_idx'), models.Index(fields=['first_name', 'last_name'], name='employees_first_n_235346_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'email'), name='unique_email_per_organization')],
            },
        ),
        migrations.CreateModel(
            name='RateLimitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField(auto_now_add=True)),
                ('last_request', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_search.organization')),
            ],
            options={
                'db_table': 'rate_limit_records',
                'indexes': [models.Index(fields=['ip_address', 'window_start'], name='rate_limit__ip_addr_d9f0b4_idx')],
            },
        ),
    ]
